### ISSUE TITLE
Something wrong with license

### ISSUE THREAD

**Issue by Bemjamin** [Caphyon/advinst-github-action#14]
Hello guys,

I am trying to use the action and it is showing me this:

![image](https://github.com/Caphyon/advinst-github-action/assets/1276294/e063fadb-ee17-48fa-9a89-b94da6a27936)

But we do have a professional license:

![image](https://github.com/Caphyon/advinst-github-action/assets/1276294/26846e37-d6e6-4e00-8fa8-399729706d6c)

Am I missing something? Thank you

**Comment by BogdanMitrache** [comment]
Hi @Bemjamin,

Are you targeting a version newer than 17.5 in your GH action?

`advinst-version: '17.5'`

Since your maintenance expired in 2020 any Advanced Installer build/project that tries to use a newer version will revert to trial. You can still use v17.5 or older.

Also please note that we recently released a [v2 major upgrade](https://github.com/Caphyon/advinst-github-action/blob/main/CHANGELOG.md) for your GH action which requires you to use an Advanced Installer version released in the last 2 years. However, the error you get is different from the limitation included in the latest release. Of course, you can still target the older of our action if you don't renew your maintenance.

**Comment by Bemjamin** [comment]
Nice, I put the version but now I think there is something wrong with the powershell:

![image](https://github.com/Caphyon/advinst-github-action/assets/1276294/6271e0be-bdeb-4598-8866-31e41f6b6a25)

Is it normal to take more than 30 min to create the COM object ? Or the version 17.5 doesn't support it ?

**Comment by BogdanMitrache** [comment]
We just tested v 17.5 and  seems to be working normally,do you still get this problem? Please try a command line build of your project on your local machine to confirm the project builds ok/faster on your machine.

```
Run caphyon/advinst-github-action@v1.0
Advanced Installer Tool Deploy
  Checking cache for advinst tool with version: 17.5
  Tool not found in cache
  Downloading advinst tool with version: 17.5
  Extracting advinst tool
  C:\Windows\system32\msiexec.exe /a D:\a\_temp\ab4b7f2b-049f-457e-9d35-f62d08f0ca26 TARGETDIR=D:\a\_temp\advinst /qn
  Enabling advinst COM interface
  C:\hostedtoolcache\windows\advinst\17.5\x86\bin\x86\advancedinstaller.com /REGSERVER
1s
Run # Load the AIP project from checkout location 
  
AIP: D:\a\Advinst-github-actions\Advinst-github-actions\digital signature.aip
Saved successfully
Checking builds status
Build required.
[ DefaultBuild ]
Building package: 
D:\a\Advinst-github-actions\Advinst-github-actions\setup\MyProject.msi
Prepare build
Detecting MSI incompatible resources
Creating MSI database
Writing Summary Information
Validating MSI

```

**Comment by Bemjamin** [comment]
Hello, I changed the way we were building everything and now it's working. Thank you
